alias vi='vim'
alias rm='rm -i'
alias prj='cd ~/Projects'
alias gl1='git log --oneline -40'
alias glg='git log --oneline --graph -40'

alias k8s='cd /home/hmchen/Projects/DevOps/CICD/k8sFund-LFS258'

