version: '3'
services:
    dockerapp:
        image: dockerapp:v0.5
        container_name: dockerappv0.5
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks: 
            - my_net
        privileged: true
    redis:
        image: redis:3.2.0
        container_name: redis
        networks:
            - my_net
        privileged: true
networks:
    my_net: 
        driver: bridge
