FROM python:3.5
RUN pip install Flask==0.11.1 redis==2.10.6
RUN useradd -ms /bin/bash james
USER james
WORKDIR /app
COPY app /app
CMD ["ls". "-al"
CMD ["chmod", "+rx", "app.py"] 
CMD ["ls". "-al"
CMD ["python", "app.py"] 
