version: '3'
services:
    dockerapp:
        container_name: dockerappv0.4
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks: 
            - my_net
    redis:
        container_name: redis
        image: redis:3.2.0
        networks:
            - my_net

networks:
    my_net: 
        driver: bridge
